# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mamadas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mamadas',
            old_name='nombre',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='mamadas',
            name='user',
        ),
    ]
